package com.afi.minby.settings

enum class SettingsItemType {
    SETTINGS_ITEM_PUSH_NOTIFICATION,
    SETTINGS_ITEM_CHANGE_PASSWORD,
    SETTINGS_ITEM_FACEBOOK,
    SETTINGS_ITEM_GOOGLE,
    SETTINGS_ITEM_TNC,
    SETTINGS_ITEM_PRIVACY,
    SETTINGS_ITEM_VERSION,
    SETTINGS_ITEM_LOGOUT
}